### ISSUE TITLE
use this library without composer

### ISSUE THREAD

**Issue by mrmmg** [ipinfo/php#10]
Hi
I want to use it without the composer. I tried to add files with `require_once` function nut it does not work. example: `require_once('ipinfo/src/IPinfo.php')`
can you help me?

**Comment by peter279k** [comment]
As far as I know, this package doesn't support installing without composer.

If you want to install this package without composer, you may use following PHP code snippets.

And these code snippets will help you to load `IPInfo` classes manually.

```php
<?php
/**
 * This is the bingo-functional autoloader.
 *
 * @param string $class The fully-qualified class name.
 *
 * @return void
 */
spl_autoload_register(function ($class) {

    // project-specific namespace prefix
    $prefix = 'ipinfo\\ipinfo\\IPinfo\\';

    // base directory for the namespace prefix
    $baseDir = __DIR__.'/src/';

    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relativeClass = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = $baseDir.str_replace('\\', '/', $relativeClass).'.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }
});
```

**Comment by peter279k** [comment]
Once using this manual `autoload` that I mention on previous discussion, it will be worked fine to load `IPinfo` classes.

But the `Class 'GuzzleHttp/Client' not found` will be triggered.

You have to handle manual "third-party" loader and it will be very complicated and frustrated.

IMHO, using the `composer` autoloader directly instead to avoid these issues.
