### ISSUE TITLE
 guzzlehttp/guzzle v7.2

### ISSUE THREAD

**Issue by usamawaleed** [ipinfo/php#20]
HI, 

I want to use this package into my project and my project using  guzzlehttp/guzzle v7.2 and your package is require a  guzzlehttp/guzzle v ^6.3 so I am unable to import package via composer

can you please update your package at packagist?

thanks

**Comment by peter279k** [comment]
It seems that the master branch has `guzzle` version has been defined with `^6.3||^7.0` on [composer.json](https://github.com/ipinfo/php/blob/master/composer.json) file.

And the [latest release version](https://github.com/ipinfo/php/blob/v1.1.1/composer.json) doesn't support `Guzzle` `^7.0` version.

To fix this issue, I think it should be good to release new version and this issue will be resolved :).

**Comment by UmanShahzad** [comment]
Sorry guys, I'll work on releasing the latest version soon. I may actually just release a 2.0.0 version with some more fixes along the way.

**Comment by UmanShahzad** [comment]
https://packagist.org/packages/ipinfo/ipinfo#v2.0.0
