### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by adnansyedimadi** [ipinfo/php#24]
Unable to download if you have PHP 8

Output below: 

Problem 1
    - ipinfo/ipinfo[dev-master, v2.0.0] require php ~7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - ipinfo/ipinfo 2.0.x-dev is an alias of ipinfo/ipinfo dev-master and thus requires it to be installed too.
    - Root composer.json requires ipinfo/ipinfo ^2.0.0 -> satisfiable by ipinfo/ipinfo[v2.0.0, 2.0.x-dev (alias of dev-master)].

**Comment by UmanShahzad** [comment]
Thanks @adnansyedimadi - we'll add support & testing for PHP 8 and deprecate support for 7.2.

**Comment by adnansyedimadi** [comment]
Thank you for the quick turnaround!
