### ISSUE TITLE
Features of extracting json Not working

### ISSUE THREAD

**Issue by parvezcs16** [ipinfo/php#26]
There are some features like directly getting Lattitude with $details->lattitude or $details['lattitude'] is not working, and for ipinfo.io/43.241.71.120/privacy?token=$TOKEN This part of feature is not working or I'm unable to get the result using simple php command.

**Comment by UmanShahzad** [comment]
@parvezcs16 it's being spelled wrong: `lattitude` -> `latitude`.

> for ipinfo.io/43.241.71.120/privacy?token=$TOKEN This part of feature is not working or I'm unable to get the result using simple php command.

What exactly is not working here? Are you putting in a valid token for $TOKEN? What php command?

**Comment by coderholic** [comment]
> What exactly is not working here? Are you putting in a valid token for $TOKEN? What php command?

I don't think we support any of the privacy fields in the SDK yet, do we?

**Comment by UmanShahzad** [comment]
@coderholic all interpreted language SDKs will return all new fields automatically without any change, and statically typed language SDKs either won't or will only support a "generic hashtable" for fields that aren't recognized yet in the code.

For PHP, here's the proof of privacy fields being supported:

https://github.com/ipinfo/php/blob/master/tests/IPinfoTest.php#L86-L116

These tests all pass.

**Comment by UmanShahzad** [comment]
@parvezcs16 hey, just asking so I can know whether to close this - was your problem solved?

**Comment by UmanShahzad** [comment]
@parvezcs16 closing this assuming your issue is solved; if it is not, please re-open and ping me.
