### ISSUE TITLE
Token Referrer restriction with PHP Lib

### ISSUE THREAD

**Issue by oliveratgithub** [ipinfo/php#38]
When using a Domainname Referrer restriction on my token, the PHP library fails to fetch user details with an error

400 Bad Request

I assume this is because my script runs Serverside hence not having a referrer http header.

Any ideas how to overcome this? Like can I force pass a referrer serverside to the IPinfo Library?

**Comment by UmanShahzad** [comment]
@oliveratgithub right now there's no way to force override the headers that this library passes, but we could allow it for most headers, including referrer.

The only thing I'm wondering is what the purpose was of using the referrer header if you are using your token on the server-side. The referrer header restriction feature is primarily to prevent abuse on the frontend.

**Comment by oliveratgithub** [comment]
@UmanShahzad Thanks for your reply. It was for a precaution in case the key would be leaked.

Anyhow, I totally overlooked that there‘s also an IP-based whitelisting for a token - so this is the way to go when using the PHP lib.
