### ISSUE TITLE
More info on why response object can be null when calling IPinfo::getDetails()

### ISSUE THREAD

**Issue by khalyomede** [ipinfo/php#53]
Hi, I am using the package to get info about a specific ip, and sometimes, in a context I do not understand yet, I get empty (null) response when calling `IPinfo::getDetails()`. I would like to know why it can return null (is it because the API throttle, server error, or any other reason?).

Not that no `IPinfoException` is thrown, I just get `null` as a result.

Also not that when I retry a few moment later the same request, it gets the result without issues.

If I know the reason I can take required measures to mitigate the issue. Thank you.

**Comment by rm-Umar** [comment]
@khalyomede I can't think of any possible scenario where you can get a `null` only as result. We are making an `HTTP` request directly to our API and then parsing the json and then creating `Details` object from that. If for some reason our API returns `null` response (I can't think of any possible scenario for that as well) then it should be returning `null` for almost all fields(in the case of bogon as well). 
I don't know how to replicate this error so the only solution I can suggest is that you can do if check on the response object to check if it's not bogon and still the value you want to access (for example `lon` and `lat`) is null you can simply do a retry on that IP.

**Comment by coderholic** [comment]
@khalyomede do you have any example IPs that consistently trigger this behavior that you can share with, to help us investigate further?

**Comment by laboni999** [comment]
https://github.com/khalyomede

**Comment by khalyomede** [comment]
@coderholic sure, I had the issue retrying 2 times for these IP:

- 80.215.225.53
- 37.170.156.217

**Comment by UmanShahzad** [comment]
@khalyomede thanks a lot man. Do you have the same issue repeatedly or is it random?

@rm-Umar can we test those two IPs via the PHP SDK specifically? Data comes back fine from other places, wonder if this is specific to the PHP SDK. Note, it has valid carrier data, that may potentially cause something.

**Comment by khalyomede** [comment]
@UmanShahzad I had 2 times a null response retrying for these IP, I will test again today to see if it works and I'll keep you posted

**Comment by khalyomede** [comment]
Good evening everyone, I confirm you retrying IP 37.170.156.217 keeps returning an error on my end. Not sure if you guys were able to reproduce it on your side as well?

**Comment by rm-Umar** [comment]
> Good evening everyone, I confirm you retrying IP 37.170.156.217 and 80.215.225.53 keeps returning an error on my end. Not sure if you guys were able to reproduce it on your side as well?

I'll check and let you know soon.

**Comment by rm-Umar** [comment]
@khalyomede I just tried and I am still not successful to replicate the issue. It's always giving me the response. I even tried an infinite loop for 10mins to check but no luck. If you face this issue again can you kindly post the output here?

**Comment by khalyomede** [comment]
Sure, this doesn't happen anymore so I'll close the issue for the moment thanks for the help guys!

**Comment by khalyomede** [comment]
Hi again, I just had the issue with this IP 94.228.190.38, and I found out the property "hostname" is not set, is it expected?

```php
use Dotenv\Dotenv;
use ipinfo\ipinfo\IPinfo;

require __DIR__ . "/vendor/autoload.php";

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

$client = new IPinfo($_ENV["IPINFO_ACCESS_TOKEN"]);
$details = $client->getDetails("94.228.190.38");

print_r($details);
```

```
ipinfo\ipinfo\Details Object
(
    [ip] => 94.228.190.38
    [city] => Paris
    [region] => Île-de-France
    [country] => FR
    [loc] => 48.8574,2.3795
    [org] => AS34177 CELESTE SAS
    [postal] => 75127 CEDEX 11
    [timezone] => Europe/Paris
    [country_name] => France
    [is_eu] => 1
    [country_flag] => Array
        (
            [emoji] => 🇫🇷
            [unicode] => U+1F1EB U+1F1F7
        )

    [country_currency] => Array
        (
            [code] => EUR
            [symbol] => €
        )

    [continent] => Array
        (
            [code] => EU
            [name] => Europe
        )

    [latitude] => 48.8574
    [longitude] => 2.3795
    [all] => Array
        (
            [ip] => 94.228.190.38
            [city] => Paris
            [region] => Île-de-France
            [country] => FR
            [loc] => 48.8574,2.3795
            [org] => AS34177 CELESTE SAS
            [postal] => 75127 CEDEX 11
            [timezone] => Europe/Paris
            [country_name] => France
            [is_eu] => 1
            [country_flag] => Array
                (
                    [emoji] => 🇫🇷
                    [unicode] => U+1F1EB U+1F1F7
                )

            [country_currency] => Array
                (
                    [code] => EUR
                    [symbol] => €
                )

            [continent] => Array
                (
                    [code] => EU
                    [name] => Europe
                )

            [latitude] => 48.8574
            [longitude] => 2.3795
        )

)
```

**Comment by UmanShahzad** [comment]
@khalyomede it's expected:

```bash
$ nslookup 94.228.190.38
** server can't find 38.190.228.94.in-addr.arpa: NXDOMAIN
```
