### ISSUE TITLE
Error with cache key

### ISSUE THREAD

**Issue by Arnold-Pham** [ipinfo/php#67]
I tried for the first time the API, with a simple symfony code I get the error:

`Cache key "xxxx:1" contains reserved characters "{}()/\@:"`

With `xxxx` being the ip adress of my server.

```
$client = new IPinfo($access_token);
$details = $client->getDetails($_SERVER["REMOTE_ADDR"]);
```

I tried setting the ip_address myself, and always the same result, the code add a ":1" at the end of my IP.

**Comment by UmanShahzad** [comment]
Thanks, fixed in https://github.com/ipinfo/php/commit/6f319c676aef8e7954db05b5cf978acb953062f2

Will release 3.1.2 soon
