### ISSUE TITLE
Support batch ops

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/php#7]
https://ipinfo.io/developers/batch

Take into account use cases like https://github.com/ipinfo/python/issues/35 to ensure batch ops support is scalable & robust.

**Comment by HEINMINKYAWHTWE** [comment]
I Love Children

**Comment by HEINMINKYAWHTWE** [comment]
I Love Children.

**Comment by HEINMINKYAWHTWE** [comment]
laylwintthu396@gmail.com

**Comment by UmanShahzad** [comment]
Will be available in v2.3.0.
