### ISSUE TITLE
Can I use downloaded Geolocation API database to initialize this client?

### ISSUE THREAD

**Issue by cawa-93** [ipinfo/php#71]
As far as I understand, this client makes api requests ещ ipinfo.io. I was wondering if I purchase a geolocation database (I need it for other purposes as well), can I somehow initialize the client with data from the database. So that it does not make any requests over the network and works only with local data?

**Comment by UmanShahzad** [comment]
@cawa-93 there is no PHP database SDK right now, but there is a Python one: https://github.com/ipinfo/python-db

We have it in the plans some time later this year to make a PHP one though!
