### ISSUE TITLE
Not working with ipv6

### ISSUE THREAD

**Issue by DevOwais** [ipinfo/php#8]
Hello, 

I found that it is not working with ipv6. As I am not getting location for ipv6 please update it as soon as posible

**Comment by coderholic** [comment]
We support IPv6 address lookups, but only over IPv4 connections currently, eg:

```
$ curl https://ipinfo.io/2a03:2880:f003:c07:face:b00c::2
{
  "ip": "2a03:2880:f003:c07:face:b00c::2",
  "city": "",
  "region": "",
  "country": "IE",
  "loc": "53.0000,-8.0000",
  "org": "AS32934 Facebook, Inc.",
  "readme": "https://ipinfo.io/missingauth"
}
```

Are you reporting a connection issue, or a specific IPv6 issue with the library?

**Comment by DevOwais** [comment]
Thankyou for your response.

This issue has been resolved.
